### ISSUE TITLE
document how to use adoc procedure correctly

### ISSUE THREAD

**Issue by jcayouette** [SUSE/doc-susemanager#205]
Lana found a bug in how the pdf procedure is rendering, we are not sure if it is due to xslt, or to a formatting issue. 

Explore the correct way to make a procedure then check to see how it is rendered in html and pdf.

**Comment by Loquacity** [comment]
Copying in correspondence on this:

**Comment by Loquacity** [comment]
Hi Joseph and Karl!

Hoping you can help me work out what's going on here. I've attached
three screenshots:

1. In my text editor, note the two procedure headings. I can't see a
difference in how they're formatted.

2. In the adoc preview tool, both headings have rendered correctly (and
in exactly the same way).

3. In the generated PDF, the first heading is bold and inline, and the
second has rendered correctly.

Any hints? I'm stumped. This is happening throughout the book.

Lana
![procedurebug_editor](https://user-images.githubusercontent.com/3914967/46057854-259df280-c19b-11e8-979a-276a90170b14.png)
![procedurebug_pdf](https://user-images.githubusercontent.com/3914967/46057855-259df280-c19b-11e8-8650-001ced175834.png)
![procedurebug_preview](https://user-images.githubusercontent.com/3914967/46057858-26368900-c19b-11e8-92af-e418e3618fa7.png)

**Comment by Loquacity** [comment]
Sep 25 18:58:46 <jcayouette>	Try moving the uppermost heading directly above the first list item
Sep 25 18:58:49 <jcayouette>	This is best practice.
Sep 25 18:58:55 <Loquacity>	oh, no intro para?
Sep 25 18:59:48 <jcayouette>	It may be a bug.
Sep 25 18:59:56 <jcayouette>	moment Ill look this up
Sep 25 19:00:30 <Loquacity>	it just seems odd to me that the preview tool renders it, but the build isn't
Sep 25 19:00:40 <Loquacity>	i was wondering if something was breaking in the xml conversion
Sep 25 19:00:53 <jcayouette>	It could also be the stylesheet
Sep 25 19:01:00 <jcayouette>	The adoc and xml are probably fine
Sep 25 19:01:09 <jcayouette>	most likely its caused by some weird xslt bug
Sep 25 19:01:51 <jcayouette>	What I would do, is make a subsection, intro, .procedure then list
Sep 25 19:01:59 <jcayouette>	I think that will clear it up for both procedures.
Sep 25 19:02:19 <Loquacity>	that's terrible form
Sep 25 19:02:29 <jcayouette>	oh right
Sep 25 19:02:30 <Loquacity>	(from a writing perspective, i mean)
Sep 25 19:02:32 <jcayouette>	sorry, skip the section
Sep 25 19:02:48 <jcayouette>	intro, then procedure.
Sep 25 19:02:56 <Loquacity>	yeah, that's the bit that i mean
Sep 25 19:03:05 <jcayouette>	Im not sure though, you have a parent section right?
Sep 25 19:03:08 <jcayouette>	So you could go
Sep 25 19:03:12 <jcayouette>	== Some title
Sep 25 19:03:15 <jcayouette>	text
Sep 25 19:03:18 <Loquacity>	if the intro is directly relevant to the procedure (not to the general concept), then it needs to go in there
Sep 25 19:03:28 <jcayouette>	=== formula procedure
Sep 25 19:03:30 <jcayouette>	intro
Sep 25 19:03:35 <jcayouette>	.procedure
Sep 25 19:03:39 <jcayouette>	. list1
Sep 25 19:03:41 <jcayouette>	.list2
Sep 25 19:03:56 <Loquacity>	yeah, i get what you're saying
Sep 25 19:03:59 <jcayouette>	true, I get your point.
Sep 25 19:04:02 <Loquacity>	but it's about where that content is relevant
Sep 25 19:04:16 <jcayouette>	ok then just try this
Sep 25 19:04:19 <jcayouette>	.procedure
Sep 25 19:04:21 <jcayouette>	intro
Sep 25 19:04:25 <jcayouette>	with no linebreak
Sep 25 19:04:43 <Loquacity>	also, that ".Procedure:" formatting is just a sub-heading, right? it shouldn't matter whether it's prose or a dot point that comes after it
Sep 25 19:04:49 <Loquacity>	hrm, ok
Sep 25 19:04:51 <Loquacity>	i can try that
Sep 25 19:04:58 <jcayouette>	Im not sure, I have not run into this one :D
Sep 25 19:05:09 <jcayouette>	I can test it here if you point me to the correct document.
Sep 25 19:05:36 <jcayouette>	That is really weird behavior.
Sep 25 19:05:42 <Loquacity>	yeah, it's in the entire book
Sep 25 19:06:04 <jcayouette>	Maybe before that procedure, there is some unclosed block, or extra concat.
Sep 25 19:06:05 <Loquacity>	i noticed it in the install chapter too
Sep 25 19:06:24 <Loquacity>	https://github.com/SUSE/doc-susemanager/blob/develop/adoc/book_retail_getting_started.adoc
Sep 25 19:06:28 <jcayouette>	thanks
Sep 25 19:06:43 <jcayouette>	which chapter?
Sep 25 19:06:55 <Loquacity>	that example is specifically in the admin chapter
Sep 25 19:12:42 <jcayouette>	ah I think you are missing a + after the second note.
Sep 25 19:13:11 <Loquacity>	hrm, possibly. i tend to forget about them
Sep 25 19:13:17 <Loquacity>	that shouldn't break the heading, thoguh
Sep 25 19:13:19 <Loquacity>	though*
Sep 25 19:13:21 <jcayouette>	but I am not certain :D
Sep 25 19:13:29 <jcayouette>	It renders fine for me
Sep 25 19:13:34 <jcayouette>	Im thinking this is a stylesheet bug from doc team
Sep 25 19:15:02 <jcayouette>	try this formatting?
Sep 25 19:15:03 <jcayouette>	[steps]
Sep 25 19:15:03 <jcayouette>	.Procedure: Create a Hardware Type Group
Sep 25 19:15:40 <jcayouette>	Im not sure we need to add the procedure: part
Sep 25 19:15:48 <jcayouette>	I think if you use [steps] then a title
Sep 25 19:16:00 <jcayouette>	when we convert to xml steps is translated to a procedure.
Sep 25 19:16:13 <Loquacity>	huh, interesting idea
Sep 25 19:16:20 <Loquacity>	i'll give that a try
Sep 25 19:16:23 <jcayouette>	ok


Sep 25 19:38:35 <jcayouette>	The best thing you could do, would be to build the xml
Sep 25 19:39:10 <jcayouette>	so `make book-to-set-suma`
Sep 25 19:39:19 <jcayouette>	then check the generated xml
Sep 25 19:39:23 <jcayouette>	and see how the xml structure looks
Sep 25 19:39:37 <jcayouette>	that might tip us off :)
Sep 25 19:41:55 <jcayouette>	if both procedures look the same in the xml its an xslt bug.

**Comment by Loquacity** [comment]
OK, so I checked the generated XML, and it is definitely processing
differently based on the presence (or otherwise) of a para between the
title and the steps. So if you go straight to steps, it becomes an
orderedlist (which is being rendered correctly in the final), but the
addition of the para makes it a formalpara and starts the orderedlist
after the para (which is being rendered as inline bold).

To wit:

> <orderedlist numeration="arabic">
>
> <title>Procedure: Apply and configure the Saltboot Formula</title>
>
> <listitem><para>Open the details page for your new hardware group, and
> navigate to the <literal role="guimenu">Formulas</literal>
> tab.</para></listitem>
>
vs

> <formalpara>
>
> <title>Procedure: Create a Hardware Type Group</title>
>
> <para>For this procedure, you will require the system manufacturer
> name and product name for your terminal.</para>
>
> </formalpara>
>
> <orderedlist numeration="arabic">
>
> <listitem><para>Determine the hardware type group name.
> Prefix the name with <literal role="systemitem">HWTYPE:</literal>,
> followed by the system manufacturer name and product name, separated
> by a hyphen.</para></listitem>
>
Adding the [steps] notation before the title doesn't change this
behaviour, except for making the orderedlist declare a numeration style
of "steps", which then breaks the build (lol). Also, I couldn't find
anything online about usage for this notation, so it's possible I'm
doing it wrong. I've asked on a forum I'm on, though, so someone might
pop up with info for me on that.

So I think we're back to "don't put a paragraph between the Procedure
title and the steps", which is untenable from a writing perspective. You
simply must, in many cases, include information there. Can we adjust how
the XML is generated to amend this behaviour?

Lana

**Comment by Loquacity** [comment]
I don't think there's anything further to do here. We have a workaround.
