### ISSUE TITLE
CPU requirements for the server and x86_64 are not clear

### ISSUE THREAD

**Issue by juliogonzalez** [SUSE/doc-susemanager#241]
Right now it reads:

> Multi-core 64-bit CPU

# Problem

We are having situations where a 2 core CPU, with each core at 1800Mhz is not enough, and we get ISE at some situations because of ProxyTimeouts waiting HTTP responses while playing with the products page at the same time reposync is running.

So the question is: would we support a customer running an Intel Celeron x86_64 with 2 cores, as long as memory and storage are OK?

For example the Celeron 2970M from 2014 (https://ark.intel.com/products/81014)

This is even more critical for Uyuni, as I am pretty sure that some users will be using consumer grade hardware for testing.

# Solution

Not clear, but as a minimum, maybe we should specify the number of cores (as we do for PowerPC):

> Minimum 4 dedicated cores

I am not so sure about the frequency :-(

But anyway, I think this is something to be discussed with engineering as well.

**Comment by jcayouette** [comment]
hm good point :)

**Comment by Loquacity** [comment]
From IRC:
Oct 16 19:25:08 <ke>	I think we should raise the HW requirements
Oct 16 19:25:38 <juliogonzalez>	ke: most probably, yes
Oct 16 19:25:51 <juliogonzalez>	IMHO we should talk about this before Uyuni goes out
Oct 16 19:26:01 <Loquacity>	juliogonzalez: looks like we need to specify quad-core +
Oct 16 19:26:07 <juliogonzalez>	(because of what I mentioned about users using computer grade hardware)
Oct 16 19:26:34 <juliogonzalez>	I mean "consumer" :-P
Oct 16 19:27:13 <juliogonzalez>	Loquacity: makes sense, the thing is that in theory it is working with two, as long as the frequency is high enough
Oct 16 19:27:33 <juliogonzalez>	but if course, I think it's easier to say "hey, get at least X cores"
Oct 16 19:27:41 <juliogonzalez>	easier and safer
Oct 16 19:27:54 <juliogonzalez>	but I'd like more feedback, and a test with Uyuni using 4 cores
>8 snip 8<
Oct 16 19:28:21 <Loquacity>	yeah, it doesn't stop people using less, it just makes it clear that you might run across some issues
Oct 16 19:28:50 <juliogonzalez>	"you are on your own if you use less", basically
Oct 16 19:28:53 <juliogonzalez>	for both SUMA and Uyuni
>8 snip 8<
Oct 16 19:33:04 <jcayouette>	juliogonzalez, nice catch
Oct 16 19:34:22 <jcayouette>	juliogonzalez, I think most consumers should be running at least a quad core. However a note would be good that they may have issues on anything lower.

**Comment by Loquacity** [comment]
Please review: https://github.com/SUSE/doc-susemanager/pull/295
