### ISSUE TITLE
Ubuntu missing as supported client in table overview

### ISSUE THREAD

**Issue by cduch** [SUSE/doc-susemanager#508]
the list is missing Ubuntu:
https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-getting-started/html/book.suma.getting-started/quickstart.chapt.overview.requirements.html#quickstart.sect.prereq.clientos

see release notes:
https://www.suse.com/releasenotes/x86_64/SUSE-MANAGER/3.2/#_support_for_ubuntu_clients

**Comment by Loquacity** [comment]
Hi there! My understanding is that Ubuntu client support was added in 3.2.7. Since the 3.2 documentation covers all  3.2.x releases, and Ubuntu is only covered for one minor release, it isn't reasonable to include it in the table. I can confirm that the table has been updated for the 4.0 documentation, though: https://opensource.suse.com/doc-susemanager/suse-manager/installation/client-requirements.html

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> Hi there! My understanding is that Ubuntu client support was added in
> 3.2.7. Since the 3.2 documentation covers all 3.2.x releases, and Ubuntu
> is only covered for one minor release, it isn't reasonable to include it
> in the table.

:+1:
Yes, I'd like us (documentarians and developers) to pay more attention
to those issues.  We (documentarians) need to be notified accurately and
in a timely manner.  It's not enough that we see a list about all the
implemented changes a few days before the release (MU).

> I can confirm that the table has been updated for the 4.0
> documentation, though:
> https://opensource.suse.com/doc-susemanager/suse-manager/installation/client-requirements.html
:clapping_hands:

-- 
Karl Eichwalder            SUSE Linux GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Mary Higgins, Sri Rasiah, HRB 21284 (AG Nürnberg)
